project:
  type: website
  output-dir: .

website:
  title: "CycleVision3"
  favicon: favicon/favicon-32x32.png #https://www.flaticon.com/fr/icone-gratuite/velo-de-route_14886
  navbar:
    left:
      - href: index.qmd
        text: Le vélo à Montpellier
      - text: Travaux 
        menu:
          - text: "Analyse des données"
            href: analyse_donnees.qmd
          - text: "Cartes"
            href: maps.qmd
          - text: "Vidéos"
            href: videos.qmd 
      - href: docu.qmd
        text: Documentation
      - href: auteurs.qmd
        text: Auteurs   

    right:
      - text: "<img src='https://upload.wikimedia.org/wikipedia/fr/thumb/f/f6/Logo_Velomagg%27.svg/266px-Logo_Velomagg%27.svg.png?20080201004526' alt='Bicycle Logo' style='height:30px; vertical-align:middle;'>"
        href: https://www.tam-voyages.com/presentation/?rub_code=1&thm_id=6

format:
  html:
    theme: flatly
    #theme: materia
    #theme: morph
    #theme: simplex
    #theme: superhero
    #theme: cyborg
    css: styles.css
    toc: true
    include-after-body: _footer.html

execute:
  freeze: auto
  enabled: true
  python: python3

