
project:
  type: website
  output-dir: docs # Quarto place les fichiers générés du site dans un dossier docs

website:
  title: "CycleVision3"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



