project:
  type: website
  output-dir: .

website:
  title: "CycleVision3"
  navbar:
    left:
      - href: index.qmd
        text: Le vélo à Montpellier
      - text: Travaux 
        menu:
          - text: "Analyse des données"
            href: projet1.qmd
          - text: "Cartes"
            href: projet2.qmd
          - text: "Vidéos"
            href: projet3.qmd 
      - href: docu.qmd
        text: Documentation
      - href: auteurs.qmd
        text: Auteurs   

    right:
      - text: "<img src='https://upload.wikimedia.org/wikipedia/fr/thumb/f/f6/Logo_Velomagg%27.svg/266px-Logo_Velomagg%27.svg.png?20080201004526' alt='Bicycle Logo' style='height:30px; vertical-align:middle;'>"
        href: https://www.tam-voyages.com/presentation/?rub_code=1&thm_id=6

format:
  html:
    theme: flatly
    #theme: materia
    #theme: morph
    #theme: simplex
    #theme: superhero
    #theme: cyborg
    css: styles.css
    toc: true
    include-in-header: []
    include-before-body: []
    include-after-body: _footer.html

execute:
  freeze: auto
  enabled: true
  python: python3

