
project:
  type: website
  output-dir: .

website:
  title: "CycleVision3"
  navbar:
    left:
      - href: index.qmd
        text: Le vélo à Montpellier
      - text: Travaux 
        menu:
          - text: "Analyse des données"
            href: projet1.qmd
          - text: "Cartes"
            href: projet2.qmd
          - text: "Vidéo"
            href: projet3.qmd 
      - href: docu.qmd
        text: Documentation
      - href: auteurs.qmd
        text: Auteurs   
    right:
      - icon: "images/logogithub.png"
        url: "https://github.com/mscaia/PROJ_HAX712X"

format:
  html:
    css: styles.css
    toc: true
    include-in-header: []
    include-before-body: []
    include-after-body: _footer.html

execute:
  freeze: auto
  enabled: true
  python: python3

