
project:
  type: website
  output-dir: .

website:
  title: "CycleVision3"
  navbar:
    left:
      - href: index.qmd
        text: Le vélo à Montpellier.
      - href: docu.qmd
        text: Documentation
      - href: auteurs.qmd
        text: Auteurs
    
    right:
      - icon: "images/logogithub.png"
        url: "https://github.com/mscaia/PROJ_HAX712X"
        
format:
  html:
    #theme: united
    css: styles.css
    toc: true



