---
title: "Contributeurs"
format: html
---
Nous sommes étudiants en Master 1 Statistique et **Science des Données (SSD)** à l’Université de Montpellier. Dans le cadre du cours *Développement Logiciel*, nous avons collaboré sur le projet **CycleVision3**, combinant nos compétences pour concevoir une solution innovante dédiée à l’analyse du trafic cycliste.
---

<table style="width: 100%; border: none; border-spacing: 20px;">

  <tr>
    <!-- Person 1 -->
    <td style="width: 45%; vertical-align: top; padding: 10px;">
      <h5><strong>ARMAND Charlotte</strong></h5>
      <p><em>Création de cartes interactives et prévisions de trafic.</em></p>
      <ul>
        <li><a href="mailto:charlotte.armand@etu.umontpellier.fr">Email</a></li>
        <li><a href="https://github.com/CharlotteARMAND">GitHub Profile</a></li>
      </ul>
    </td>

    <!-- Person 2 -->
    <td style="width: 45%; vertical-align: top; padding: 10px;">
      <h5><strong>CONDAMY Fabian</strong></h5>
      <p><em>Développement et déploiement du site web.</em></p>
      <ul>
        <li><a href="mailto:fabian.condamy@etu.umontpellier.fr">Email</a></li>
        <li><a href="https://github.com/FabianCondamy">GitHub Profile</a></li>
      </ul>
    </td>
  </tr>

  <tr>
    <!-- Person 3 -->
    <td style="width: 45%; vertical-align: top; padding: 10px;">
      <h5><strong>SCAIA Matteo</strong></h5>
      <p><em>Analyse de données et création de cartes interactives et vidéos.</em></p>
      <ul>
        <li><a href="mailto:matteo.scaia@etu.umontpellier.fr">Email</a></li>
        <li><a href="https://github.com/mscaia">GitHub Profile</a></li>
      </ul>
    </td>

    <!-- Person 4 -->
    <td style="width: 45%; vertical-align: top; padding: 10px;">
      <h5><strong>STETSUN Kateryna</strong></h5>
      <p><em>Tests et documentation du projet, assistance développement du site web.</em></p>
      <ul>
        <li><a href="mailto:kateryna.stetsun@etu.umontpellier.fr">Email</a></li>
        <li><a href="https://github.com/KatyaStetsun">GitHub Profile</a></li>
      </ul>
    </td>
  </tr>

</table>

---

<details>
<summary>**LICENCE**</summary>

**Copyright 2024 SCAIA Matteo, ARMAND Charlotte, CONDAMY Fabian, STETSUN Kateryna**  

Permission est accordée gratuitement à toute personne obtenant une copie de ce logiciel et des fichiers de documentation associés (le "Logiciel"), d'utiliser le Logiciel sans restriction, y compris, sans limitation, les droits d'utiliser, copier, modifier, fusionner, publier, distribuer, sous-licencier et/ou vendre des copies du Logiciel, sous réserve des conditions suivantes :  

La notice de copyright ci-dessus et cette permission doivent être incluses dans toutes les copies ou parties substantielles du Logiciel.  

LE LOGICIEL EST FOURNI "EN L'ÉTAT", SANS GARANTIE D'AUCUNE SORTE, EXPRESSE OU IMPLICITE, Y COMPRIS MAIS SANS S'Y LIMITER, LES GARANTIES DE QUALITÉ MARCHANDE, D'ADÉQUATION À UN USAGE PARTICULIER ET D'ABSENCE DE CONTREFAÇON. EN AUCUN CAS, LES AUTEURS OU DÉTENTEURS DU COPYRIGHT NE POURRONT ÊTRE TENUS RESPONSABLES DE TOUTE RÉCLAMATION, DOMMAGES OU AUTRE RESPONSABILITÉ, QUE CE SOIT DANS UNE ACTION CONTRACTUELLE, DÉLICTUELLE OU AUTRE, PROVENANT DU LOGICIEL OU DE SON UTILISATION OU D'AUTRES INTERACTIONS AVEC CELUI-CI.

</details>
