name: Run Pytest Tests

on:
  push:
    branches:
      - main  # Remplacez "main" par le nom de votre branche par défaut si nécessaire
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12  # Spécifiez la version de Python que vous utilisez

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # Exécuter les tests avec pytest et générer un rapport de couverture
        pytest tests/ --cov=Cycle3 --cov-report=xml

    - name: Upload coverage to Codecov # Suivi des rapports
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}